/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codepest.logic.utilities;

/**
 *
 * @author Prashant-PC
 */
public class ReportUtility {
  
    public static String addHeader(String reportTitle)
    {
        return  "<html>\n" +
                "<head>\n" +
                "<title>CodePest Control</title> \n" +
                "</head>\n" +
                "<body>\n" +
                "<center><h1>&lt;CodePest&gt;</h1></center>\n" +
                "<center><h1>"+reportTitle+"</h1></center>";
    }
    
    public static String addFooter()
    {
        return  "<center><p>Reports Generated By <b>CodePest</b> Tool</p></center>\n" +
                "</body>\n" +
                "</html>";
    }
}
